name: WakaTime Status Update

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: athul/wakatime-status-update@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
